<?php

namespace app\commands;

use yii\console\Controller;
use Yii;
use yii\helpers\FileHelper;

/**
 * Genera archivos de cache reemplazando getenv(), $_ENV y $_SERVER por sus valores resueltos.
 */
class ConfigController extends Controller
{
    /**
     * Alias para actionCache.
     */
    public function actionIndex()
    {
        return $this->actionCache();
    }

    /**
     * Genera archivos de cache en config/cache/.
     */
    public function actionCache()
    {
        $configDir = Yii::getAlias('@app/config');
        $cacheDir  = $configDir . '/cache';

        // 1. Cargar variables del .env usando la librería Dotenv
        $this->loadEnvs();
        // FileHelper::removeDirectory($cacheDir);

        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }



        // download from storage s3

        // remove cache folder

        // 1. Find all PHP files in config dir, excluding cache folder
        $configFiles = FileHelper::findFiles($configDir, [
            'only' => ['*.php'],
            'except' => ['cache/'], // exclude cache dir itself
            'recursive' => true,
        ]);

        foreach ($configFiles as $sourcePath) {
            // Get relative path (e.g., 'params.php' or 'subdir/config.php')
            // normalized to forward slashes for consistency if needed, though PHP handles mixed well on Windows mostly
            $relativePath = substr($sourcePath, strlen($configDir) + 1);
            $relativePath = str_replace('\\', '/', $relativePath); // normalize for output/consistency

            // Skip if it's somehow the cache dir itself (redundant safety)
            if (strpos($relativePath, 'cache/') === 0) continue;

            $source = file_get_contents($sourcePath);

            // 2. Reemplazar getenv('VAR') o getenv('VAR', 'DEFAULT') con el valor cargado
            $cached = preg_replace_callback(
                '/getenv\(\s*[\'"]([^\'"]+)[\'"]\s*(?:,\s*([^)]*))?\)/',
                function ($matches) {
                    $varName = $matches[1];
                    $default = isset($matches[2]) ? trim($matches[2]) : 'null';

                    // Buscar en el entorno (ya cargado por Dotenv)
                    $value = getenv($varName);
                    if ($value === false) {
                        $value = $_ENV[$varName] ?? $_SERVER[$varName] ?? null;
                    }

                    if ($value === null) {
                        return $default;
                    }

                    // Cast special string values to their types
                    if (is_string($value)) {
                        $lower = strtolower($value);
                        if ($lower === 'true') {
                            $value = true;
                        } elseif ($lower === 'false') {
                            $value = false;
                        } elseif ($lower === 'null') {
                            $value = null;
                        }
                    }

                    return var_export($value, true);
                },
                $source
            );

            // 3. Reemplazar $_ENV['VAR'] y $_SERVER['VAR']
            $cached = preg_replace_callback(
                '/(\$_ENV|\$_SERVER)\s*\[\s*[\'"]([^\'"]+)[\'"]\s*\]/',
                function ($matches) {
                    $varName = $matches[2];
                    $value = getenv($varName);
                    if ($value === false) {
                        $value = $_ENV[$varName] ?? $_SERVER[$varName] ?? null;
                    }

                    if ($value === null) {
                        return $matches[0];
                    }

                    // Cast special string values to their types
                    if (is_string($value)) {
                        $lower = strtolower($value);
                        if ($lower === 'true') {
                            $value = true;
                        } elseif ($lower === 'false') {
                            $value = false;
                        } elseif ($lower === 'null') {
                            $value = null;
                        }
                    }

                    return var_export($value, true);
                },
                $cached
            );

            // Inyectar cabecera de cache
            $header = "\n// Auto-generated by config/cache — " . date('Y-m-d H:i:s') . "\n// Do NOT edit manually. Run: php yii config/cache\n";
            if (strpos($cached, '<?php') !== false) {
                // Determine if it declares namespace or use statements to insert correctly? 
                // Simple append to <?php is usually safe for config files unless they are strict/psr-12 with file header docblocks.
                // But header docblocks usually come after <?php.
                $cached = preg_replace('/^<\?php/', '<?php' . $header, $cached);
            }

            // Ensure destination directory exists
            $targetPath = $cacheDir . '/' . $relativePath;
            $targetDir = dirname($targetPath);
            if (!is_dir($targetDir)) {
                FileHelper::createDirectory($targetDir);
            }

            file_put_contents($targetPath, $cached);
            $this->stdout("config/cache/{$relativePath}\n", \yii\helpers\Console::FG_GREEN);
        }

        $this->stdout("\nConfig cache generado correctamente.\n");
    }


    /**
     * Limpia la cache.
     */
    public function actionClearCache()
    {
        $cacheDir = Yii::getAlias('@app/config/cache');
        if (!is_dir($cacheDir)) {
            $this->stdout("El directorio de cache no existe.\n");
            return;
        }

        FileHelper::removeDirectory($cacheDir);
        $this->stdout("Cache eliminado recursivamente.\n");
    }

    /**
     * Carga el .env usando Dotenv si existe.
     */
    protected function loadEnvs()
    {
        $path = Yii::getAlias('@app');
        if (file_exists($path . '/.env') && class_exists('\Dotenv\Dotenv')) {
            try {
                $dotenv = \Dotenv\Dotenv::createUnsafeImmutable($path);
                $dotenv->load();
            } catch (\Exception $e) {
            }
        }
    }
}
